### ISSUE TITLE
Erro ao autenticar FaceAPI

### ISSUE THREAD

**Issue by TBertuzzi** [angelobelchior/IntelligentApp#1]
Muito Bom o App!!!

Só tive um problema : Fui executar e no meu caso ele não autenticava minha chave da API.
So funcionou quando eu alterei o método Analyze da classe Face.cs para  var client = new FaceServiceClient(Constants.FaceApiKey,"https://westcentralus.api.cognitive.microsoft.com/face/v1.0"); Passando a url do serviço.

Pode ser um erro pontual.

**Comment by angelobelchior** [comment]
Na teoria, a API deveria se resolver. Vou adicionar uma constante para o API Root para poder sere configurável :)

**Comment by TBertuzzi** [comment]
Isso q foi estranho, só nessa API deu o problema. Show !!! blz, fica mais facil se mudar no futuro! vlw angelo! e parabens novamente pelo app de exemplo!

**Comment by angelobelchior** [comment]
Atualizei a versão. Inclui as constantes de Endpoint.

**Comment by TBertuzzi** [comment]
Show! Obrigado Angelo :D
